# Generated by Django 4.2.5 on 2023-10-20 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.CharField(db_column='id_categoria', max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta1', models.TextField(db_column='Satisfacción con el sistema')),
                ('pregunta2', models.TextField(db_column='Dacilidad de uso y la amigabilidad de la interfaz')),
                ('pregunta3', models.TextField(db_column='Facilidad de usar y entender')),
                ('pregunta4', models.TextField(db_column='Frecuencia de problemas técnicos o errores')),
                ('pregunta5', models.TextField(db_column='Adaptabilidad a necesidades específicas y requisitos comerciales')),
                ('pregunta6', models.TextField(db_column='Mejoras en la eficiencia')),
                ('pregunta7', models.TextField(db_column='Utilidad de informes y análisis financieros')),
                ('pregunta8', models.TextField(db_column='Capacidad para manejar múltiples divisas y tasas de cambio')),
                ('pregunta9', models.TextField(db_column='Interrupciones en el servicio')),
                ('pregunta10', models.TextField(db_column='Perdida de datos críticos o información financiera')),
            ],
            options={
                'db_table': 'encuesta',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodotipo', models.CharField(db_column='id_metodotipo', max_length=7, primary_key=True, serialize=False)),
                ('nombre_metodo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'MetodoPago',
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id_moneda', models.CharField(db_column='id_moneda', max_length=3, primary_key=True, serialize=False)),
                ('nombre_moneda', models.CharField(max_length=255)),
                ('simbolo_moneda', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Moneda',
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id_cuenta', models.CharField(db_column='id_cuenta', max_length=24, primary_key=True, serialize=False)),
                ('nombre_cuenta', models.CharField(db_column='nombre_cuenta', max_length=100)),
                ('fk_metodo_pago', models.ForeignKey(db_column='fk_metodo_pago', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.metodopago')),
                ('fk_usuario', models.ForeignKey(db_column='fk_usuario', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Tarjeta',
            },
        ),
        migrations.CreateModel(
            name='TipoTransaccion',
            fields=[
                ('id_tipo', models.CharField(db_column='id_tipo', max_length=10, primary_key=True, serialize=False)),
                ('tipo_transaccion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'TipoTransaccion',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.CharField(db_column='id_transaccion', max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('fk_cuenta', models.ForeignKey(db_column='fk_cuenta', default=None, on_delete=django.db.models.deletion.CASCADE, to='api.tarjeta')),
                ('fk_moneda', models.ForeignKey(db_column='fk_moneda', default=None, on_delete=django.db.models.deletion.CASCADE, to='api.moneda')),
                ('fk_tipo', models.ForeignKey(db_column='fk_tipo', default=None, on_delete=django.db.models.deletion.CASCADE, to='api.tipotransaccion')),
                ('fk_usuario', models.ForeignKey(db_column='fk_usuario', default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fkcategoria', models.ForeignKey(db_column='fkcategoria', default=None, on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
            ],
            options={
                'db_table': 'Transaccion',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.CharField(db_column='id_pago', max_length=20, primary_key=True, serialize=False)),
                ('nombre_deuda', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaInicio', models.DateField()),
                ('fechaTermino', models.DateField()),
                ('frecuencia', models.CharField(max_length=255)),
                ('fk_usuario', models.ForeignKey(db_column='fk_usuario', default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Pago',
            },
        ),
        migrations.CreateModel(
            name='MetaFinanciera',
            fields=[
                ('id_meta', models.CharField(db_column='id_meta', max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('objetivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaInicio', models.DateField()),
                ('fechaTermino', models.DateField()),
                ('fk_usuario', models.ForeignKey(db_column='fk_usuario', default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MetaFinanciera',
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='fk_tipo',
            field=models.ForeignKey(db_column='fk_tipo', default=None, on_delete=django.db.models.deletion.CASCADE, to='api.tipotransaccion'),
        ),
        migrations.CreateModel(
            name='Ahorro',
            fields=[
                ('id_ahorro', models.CharField(db_column='id_ahorro', max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('fk_cuenta', models.ForeignKey(db_column='fk_cuenta', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.tarjeta')),
                ('fk_usuario', models.ForeignKey(db_column='fk_usuario', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Ahorro',
            },
        ),
    ]
