# Generated by Django 4.2.5 on 2023-10-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoDePago',
            fields=[
                ('id_metodotipo', models.IntegerField(db_column='id_metodotipo', primary_key=True, serialize=False)),
                ('nombre_metodo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'MetodoDePago',
            },
        ),
    ]
