# Generated by Django 4.2.5 on 2023-09-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gener',
            fields=[
                ('idGenero', models.IntegerField(db_column='idGenero', primary_key=True, serialize=False)),
                ('tipoGenero', models.TextField(db_column='tipoGenero')),
            ],
            options={
                'db_table': 'Generos',
            },
        ),
    ]
