# Generated by Django 4.2.5 on 2023-10-04 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_metododepago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(db_column='id_categoria', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fk_tipo', models.ForeignKey(db_column='fk_tipo', default=None, on_delete=django.db.models.deletion.CASCADE, to='api.tipotransaccion')),
            ],
            options={
                'db_table': 'Categoria',
            },
        ),
    ]
