# Generated by Django 4.2.5 on 2023-10-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='id_transaccion',
            field=models.CharField(db_column='id_transaccion', max_length=20, primary_key=True, serialize=False),
        ),
    ]
