# Generated by Django 4.2.5 on 2023-09-13 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gener'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gener',
            new_name='Genero',
        ),
        migrations.AddField(
            model_name='alumno',
            name='fk_genero',
            field=models.ForeignKey(db_column='fk_genero', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.genero'),
        ),
    ]
