# Generated by Django 4.2.5 on 2023-10-04 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_cuenta', models.IntegerField(db_column='id_cuenta', default=1, primary_key=True, serialize=False)),
                ('nombre_cuenta', models.CharField(db_column='nombre_cuenta', max_length=100)),
                ('fk_metodo_pago', models.ForeignKey(db_column='fk_metodo_pago', default=None, on_delete=django.db.models.deletion.CASCADE, to='api.metododepago')),
                ('fk_usuario', models.ForeignKey(db_column='fk_usuario', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Cuenta',
            },
        ),
    ]
