# Generated by Django 4.2.5 on 2023-10-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_transaccion_id_transaccion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaccion',
        ),
    ]
