# Generated by Django 4.2.5 on 2023-09-13 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_gener_genero_alumno_fk_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='fk_genero',
        ),
    ]
