# Generated by Django 4.2.5 on 2023-09-13 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_alumno_fk_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='alumno_has_genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_alumno', models.ForeignKey(db_column='fk_alumno', on_delete=django.db.models.deletion.CASCADE, to='api.alumno')),
                ('fk_genero', models.ForeignKey(db_column='fk_genero', on_delete=django.db.models.deletion.CASCADE, to='api.genero')),
            ],
            options={
                'db_table': 'alumno_has_genero',
            },
        ),
    ]
