# Generated by Django 4.2.5 on 2023-10-04 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ahorro',
            fields=[
                ('id_ahorro', models.IntegerField(db_column='id_ahorro', primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('fk_cuenta', models.ForeignKey(db_column='fk_cuenta', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.cuenta')),
                ('fk_usuario', models.ForeignKey(db_column='fk_usuario', default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Ahorro',
            },
        ),
    ]
