# Generated by Django 4.2.5 on 2023-10-15 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_delete_transaccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.CharField(db_column='id_transaccion', max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('fk_cuenta', models.ForeignKey(db_column='fk_cuenta', default=None, on_delete=django.db.models.deletion.CASCADE, to='api.tarjeta')),
                ('fk_moneda', models.ForeignKey(db_column='fk_moneda', default=None, on_delete=django.db.models.deletion.CASCADE, to='api.moneda')),
                ('fk_tipo', models.ForeignKey(db_column='fk_tipo', default=None, on_delete=django.db.models.deletion.CASCADE, to='api.tipotransaccion')),
                ('fk_usuario', models.ForeignKey(db_column='fk_usuario', default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fkcategoria', models.ForeignKey(db_column='fkcategoria', default=None, on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
            ],
            options={
                'db_table': 'Transaccion',
            },
        ),
    ]
