# Generated by Django 4.2.5 on 2023-10-04 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_ahorro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.IntegerField(db_column='id_pago', primary_key=True, serialize=False)),
                ('nombre_deuda', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaInicio', models.DateField()),
                ('fechaTermino', models.DateField()),
                ('frecuencia', models.CharField(max_length=255)),
                ('fk_usuario', models.ForeignKey(db_column='fk_usuario', default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Pago',
            },
        ),
    ]
