# Generated by Django 4.2.5 on 2023-10-17 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_transaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahorro',
            name='fk_usuario',
            field=models.ForeignKey(db_column='fk_usuario', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
