# Generated by Django 4.2.5 on 2023-09-13 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_alumno_has_genero_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ahorros',
            fields=[
                ('idAhorro', models.IntegerField(db_column='idAhorro', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='cantidad')),
                ('descripcion', models.CharField(db_column='descripcion', max_length=100)),
                ('fecha', models.DateField(db_column='fecha')),
            ],
            options={
                'db_table': 'Ahorros',
            },
        ),
        migrations.CreateModel(
            name='BalanceGeneral',
            fields=[
                ('idBalance', models.IntegerField(db_column='idDeuda', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'BalanceGeneral',
            },
        ),
        migrations.CreateModel(
            name='CategoriasGastos',
            fields=[
                ('idCategoriaGasto', models.AutoField(db_column='idCategoriaGasto', default=1, primary_key=True, serialize=False)),
                ('categoria', models.CharField(db_column='categoria', max_length=100)),
            ],
            options={
                'db_table': 'CategoriasGastos',
            },
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('idCuenta', models.AutoField(db_column='idMetodo', primary_key=True, serialize=False)),
                ('numCuenta', models.CharField(db_column='numCuenta', max_length=18)),
            ],
            options={
                'db_table': 'CuentaBancaria',
            },
        ),
        migrations.CreateModel(
            name='Deudas',
            fields=[
                ('idDeuda', models.IntegerField(db_column='idDeuda', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='cantidad')),
                ('descripcion', models.CharField(db_column='descripcion', max_length=100)),
                ('fechaPago', models.DateField(db_column='fechaPago')),
            ],
            options={
                'db_table': 'Deudas',
            },
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('idGasto', models.IntegerField(db_column='idIngreso', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='cantidad')),
                ('descripcion', models.CharField(db_column='descripcion', max_length=100)),
                ('fecha', models.DateField(db_column='fecha')),
                ('fk_CategoriaIngreso', models.ForeignKey(db_column='fk_idCategoriaIngreso', on_delete=django.db.models.deletion.CASCADE, to='api.categoriasgastos')),
            ],
            options={
                'db_table': 'Gastos',
            },
        ),
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('idIngreso', models.IntegerField(db_column='idIngreso', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='cantidad')),
                ('descripcion', models.CharField(db_column='descripcion', max_length=100)),
                ('fecha', models.DateField(db_column='fecha')),
                ('fk_CategoriaIngreso', models.ForeignKey(db_column='fk_idCategoriaIngreso', on_delete=django.db.models.deletion.CASCADE, to='api.categoriasgastos')),
            ],
            options={
                'db_table': 'Ingresos',
            },
        ),
        migrations.CreateModel(
            name='MetasFinancieras',
            fields=[
                ('idMeta', models.AutoField(db_column='idMeta', default=1, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=100)),
                ('cantidad', models.IntegerField(db_column='cantidad')),
                ('fecha', models.DateField(db_column='fecha')),
            ],
            options={
                'db_table': 'MetasFinancieras',
            },
        ),
        migrations.CreateModel(
            name='MetodosPago',
            fields=[
                ('idMetodo', models.AutoField(db_column='idMetodo', default=1, primary_key=True, serialize=False)),
                ('metodo', models.CharField(db_column='metodo', max_length=30)),
            ],
            options={
                'db_table': 'MetodosPago',
            },
        ),
        migrations.CreateModel(
            name='TiposMoneada',
            fields=[
                ('idTipoMoneda', models.AutoField(db_column='idTipoMoneda', default=1, primary_key=True, serialize=False)),
                ('tipoMoneda', models.CharField(db_column='tipoMoneda', max_length=30)),
            ],
            options={
                'db_table': 'TiposMoneda',
            },
        ),
        migrations.RemoveField(
            model_name='alumno_has_genero',
            name='fk_alumno',
        ),
        migrations.RemoveField(
            model_name='alumno_has_genero',
            name='fk_genero',
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='alumno_has_genero',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.AddField(
            model_name='ingresos',
            name='fk_idTipoMoneda',
            field=models.ForeignKey(db_column='fk_idTipoMoneda', on_delete=django.db.models.deletion.CASCADE, to='api.tiposmoneada'),
        ),
        migrations.AddField(
            model_name='gastos',
            name='fk_idMetodoPago',
            field=models.ForeignKey(db_column='fk_idMetodoPago', on_delete=django.db.models.deletion.CASCADE, to='api.metodospago'),
        ),
        migrations.AddField(
            model_name='gastos',
            name='fk_idTipoMoneda',
            field=models.ForeignKey(db_column='fk_idTipoMoneda', on_delete=django.db.models.deletion.CASCADE, to='api.tiposmoneada'),
        ),
        migrations.AddField(
            model_name='deudas',
            name='fk_idTipoMoneda',
            field=models.ForeignKey(db_column='fk_idTipoMoneda', on_delete=django.db.models.deletion.CASCADE, to='api.tiposmoneada'),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='fk_idMetodo',
            field=models.ForeignKey(db_column='fk_idMetodo', on_delete=django.db.models.deletion.CASCADE, to='api.metodospago'),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='fk_idDeuda',
            field=models.ForeignKey(db_column='fk_idDeuda', on_delete=django.db.models.deletion.CASCADE, to='api.deudas'),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='fk_idGasto',
            field=models.ForeignKey(db_column='fk_idGasto', on_delete=django.db.models.deletion.CASCADE, to='api.gastos'),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='fk_idIngreso',
            field=models.ForeignKey(db_column='fk_idIngreso', on_delete=django.db.models.deletion.CASCADE, to='api.ingresos'),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='fk_idMeta',
            field=models.ForeignKey(db_column='fk_idMeta', on_delete=django.db.models.deletion.CASCADE, to='api.metasfinancieras'),
        ),
        migrations.AddField(
            model_name='ahorros',
            name='fk_CategoriaIngreso',
            field=models.ForeignKey(db_column='fk_idCategoriaIngreso', on_delete=django.db.models.deletion.CASCADE, to='api.categoriasgastos'),
        ),
    ]
