# Generated by Django 4.2.5 on 2023-10-04 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id_moneda', models.IntegerField(db_column='id_moneda', primary_key=True, serialize=False)),
                ('codigo_moneda', models.CharField(max_length=3)),
                ('nombre_moneda', models.CharField(max_length=255)),
                ('simbolo_moneda', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Moneda',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.IntegerField(db_column='id_transaccion', primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('fk_cuenta', models.ForeignKey(db_column='fk_cuenta', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.cuenta')),
                ('fk_moneda', models.ForeignKey(db_column='fk_moneda', default=None, on_delete=django.db.models.deletion.CASCADE, to='api.moneda')),
                ('fk_tipo', models.ForeignKey(db_column='fk_tipo', default=None, on_delete=django.db.models.deletion.CASCADE, to='api.tipotransaccion')),
                ('fk_usuario', models.ForeignKey(db_column='fk_usuario', default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fkcategoria', models.ForeignKey(db_column='fkcategoria', default=None, on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
            ],
            options={
                'db_table': 'Transaccion',
            },
        ),
        migrations.CreateModel(
            name='MetaFinanciera',
            fields=[
                ('id_meta', models.IntegerField(db_column='id_meta', primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('objetivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaInicio', models.DateField()),
                ('fechaTermino', models.DateField()),
                ('fk_usuario', models.ForeignKey(db_column='fk_usuario', default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MetaFinanciera',
            },
        ),
    ]
