# Generated by Django 4.2.5 on 2023-10-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_moneda_transaccion_metafinanciera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahorro',
            name='id_ahorro',
            field=models.CharField(db_column='id_ahorro', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id_categoria',
            field=models.CharField(db_column='id_categoria', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='id_cuenta',
            field=models.CharField(db_column='id_cuenta', max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='metafinanciera',
            name='id_meta',
            field=models.CharField(db_column='id_meta', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='metododepago',
            name='id_metodotipo',
            field=models.CharField(db_column='id_metodotipo', max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='id_moneda',
            field=models.CharField(db_column='id_moneda', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pago',
            name='id_pago',
            field=models.CharField(db_column='id_pago', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipotransaccion',
            name='id_tipo',
            field=models.CharField(db_column='id_tipo', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='id_transaccion',
            field=models.CharField(db_column='id_transaccion', max_length=15, primary_key=True, serialize=False),
        ),
    ]
