# Generated by Django 4.2.5 on 2023-10-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_ahorro_id_ahorro_alter_categoria_id_categoria_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE UNIQUE INDEX auth_user_email_idx ON auth_user (email);",
            "DROP INDEX auth_user_email_idx;"
        ),
    ]
