# Generated by Django 4.2.5 on 2023-10-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20231010_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneda',
            name='codigo_moneda',
        ),
        migrations.AlterField(
            model_name='moneda',
            name='id_moneda',
            field=models.CharField(db_column='id_moneda', max_length=3, primary_key=True, serialize=False),
        ),
    ]
