# Generated by Django 4.2.5 on 2023-10-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_moneda_codigo_moneda_alter_moneda_id_moneda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.PositiveIntegerField()),
            ],
        ),
    ]
