# Generated by Django 3.2.4 on 2023-11-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_encuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fechaInicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fechaTermino',
            field=models.DateTimeField(),
        ),
    ]
