# Generated by Django 3.2.4 on 2023-11-05 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20231105_0030'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='encuesta',
            table='api_encuesta',
        ),
    ]
