# Generated by Django 3.2.4 on 2023-11-05 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_encuesta_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='encuesta',
        ),
    ]
