# Generated by Django 3.2.4 on 2023-11-05 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_encuesta'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='encuesta',
            table='encuesta',
        ),
    ]
