# Generated by Django 3.2.4 on 2023-11-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_pago_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='nombre_deuda',
            field=models.CharField(max_length=50),
        ),
    ]
