# Generated by Django 3.2.4 on 2023-11-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_pago_fk_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fechaInicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fechaTermino',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
