# Generated by Django 3.2.4 on 2023-11-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20231106_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahorro',
            name='id_ahorro',
            field=models.CharField(db_column='id_ahorro', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fechaInicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fechaTermino',
            field=models.DateTimeField(),
        ),
    ]
