# Generated by Django 3.2.4 on 2024-01-05 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20231106_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='metafinanciera',
            name='fk_moneda',
            field=models.ForeignKey(db_column='fk_moneda', default='MXN', on_delete=django.db.models.deletion.CASCADE, to='api.moneda'),
        ),
    ]
